### ISSUE TITLE
Bug in byteps.mxnet broadcast_parameters when processing gluon deferred initialization parameters.

### ISSUE THREAD

**Issue by haoxintong** [bytedance/byteps#44] opened 2019-07-04 07:09 UTC
**Describe the bug**
https://github.com/bytedance/byteps/blob/f12518781ecdd807dc173e9316f8e1f1929153fa/byteps/mxnet/__init__.py#L97-L106 
When broadcast `Block.collect_params()`, in each step of loop:
1. try p.data()
2. if catch DeferredInitializationError, it call p.data() again. 

Then the same exception will be raised.

In `example/mxnet-gluon`, I use `model.summary(...)` to initialize parameters before broadcast to other processes. But there should be a better way to address it. 

One possible way is to put the broadcast in `DistributedTrainer`. When running first iter of training, all deferred initializied parameters will finish their initialization. Now we can run declare_tensor and push_pull.

**Comment by ymjiang** [comment] 2019-07-04 10:01
Thank you very much. Actually I have a few questions:

> When broadcast `Block.collect_params()`, in each step of loop:
> 1. try p.data()
> 2. if catch DeferredInitializationError, it call p.data() again.

Did you observe it in your training tasks? What could be the root cause? I am not familiar with Gluon.


> One possible way is to put the broadcast in `DistributedTrainer`. When running first iter of training, all deferred initializied parameters will finish their initialization. Now we can run declare_tensor and push_pull.

So is "model.summary(...)" your current workaround on this problem? We will definitely consider your suggestions.

**Comment by haoxintong** [comment] 2019-07-04 11:06
For a object of `Parameter`, p.data(ctx=...) returns a copy of this on one context, data() API **must** have been initialized on this context before, as the document describe.

If there is no `model.summary(dummy_data)` before broadcast, the task will fail:
```shell
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.5/site-packages/byteps-0.1.0-py3.5-linux-x86_64.egg/byteps/mxnet/__init__.py", line 99, in broadcast_parameters
    tensors.append(p.data())
  File "/home/anaconda3/lib/python3.5/site-packages/mxnet/gluon/parameter.py", line 494, in data
    return self._check_and_get(self._data, ctx)
  File "/home/anaconda3/lib/python3.5/site-packages/mxnet/gluon/parameter.py", line 208, in _check_and_get
    "num_features, etc., for network layers."%(self.name))
mxnet.gluon.parameter.DeferredInitializationError: Parameter 'hybridsequential0_conv0_weight' has not been initialized yet because initialization was deferred. Actual initialization happens during the first forward pass. Please pass one batch of data through the network before accessing Parameters. You can also avoid deferred initialization by specifying in_units, num_features, etc., for network layers.
```

When creating a gluon model (HybridBlock), it's not necessary for users to set input channel_num or shapes like fc layer, conv, etc. (which is different with tensorflow/pytorch), as mxnet will check and auto infer the correct shapes at the first forward process. So before we give an input, the params usually can't be initialized without shape infomation.

"model.summary()" will run forward, then show user the network graph, for this problem, it can be replaced by "model(dummy_data)".
```
        Layer (type)                                Output Shape         Param #
================================================================================
               Input                              (1, 1, 28, 28)               0
        Activation-1   <Symbol hybridsequential0_conv0_relu_fwd>               0
        Activation-2                             (1, 20, 24, 24)               0
            Conv2D-3                             (1, 20, 24, 24)             520
         MaxPool2D-4                             (1, 20, 12, 12)               0
        ...
        ...
       Activation-10  <Symbol hybridsequential0_dense0_relu_fwd>               0
       Activation-11                                    (1, 512)               0
            Dense-12                                    (1, 512)          410112
            Dense-13                                     (1, 10)            5130
================================================================================
```

**Comment by ymjiang** [comment] 2019-07-09 01:43
This issue has been addressed by https://github.com/bytedance/byteps/pull/48. Closing.

**Closed by ymjiang** 2019-07-09 01:43 UTC
Labels: enhancement
